# Generated by Django 4.1.7 on 2023-03-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dName', models.CharField(help_text='ປ້ອນຊື່ຂອງສາຂາຮຽນ', max_length=35)),
                ('email', models.CharField(help_text='ປ້ອນອີເມວຂອງສາຂາຮຽນ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(help_text='ປ້ອນຊື່ຂອງທ່ານ', max_length=35)),
                ('lName', models.CharField(help_text='ປ້ອນນາມສະກຸນຂອງທ່ານ', max_length=50)),
                ('email', models.CharField(help_text='ປ້ອນອີເມວຂອງທ່ານ', max_length=50)),
                ('address', models.TextField(help_text='ປ້ອນທີ່ຢູ່ຂອງທ່ານ')),
                ('age', models.IntegerField(default=17)),
                ('weight', models.FloatField(default=0.0, help_text='ປ້ອນນ້ຳໜັກຂອງທ່ານເປັນ KG')),
                ('height', models.DecimalField(decimal_places=2, help_text='ປ້ອນສ່ວນສູງຂອງທ່ານເປັນ M', max_digits=3)),
                ('status', models.BooleanField(default=False, help_text='ລະບຸສະຖານະການແຕ່ງງານຂອງທ່ານ')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Register', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
